### PR TITLE
Update RAK5010_AWS_MQTT.ino

### PR DESCRIPTION
**Pull request by myasir926**
Several changes..

### CODE REVIEW

**Comment by myasir926** [comment]
@beegee-tokyo

**Comment by beegee-tokyo** [comment]
You removed the example certificates without indicating where they should be. Users might not understand where they are coming from.
You removed as well the reading of the sensor data, which is part of the example data sent to AWS.

Feel free to use your changed examples, but we will keep this example as is.

**Comment by beegee-tokyo** [comment]
I don't understand your changes.
You removed the example certs and reading of the sensors.

The example certs are in the code so that the user knows how to add and format them.
The sensor readings are part of the example.

Feel free to use your changed code for your own use, but it does not match with the expectation we have for this example.

**Comment by myasir926** [comment]
Thanks

**Pull request closed without merging**
